/**
 * gen-icons.mjs
 * Reads selected pixelarticons SVGs and generates
 * internal/server/view/shared_icons_pixel.go
 *
 * Run: node gen-icons.mjs  (from desktop-app/editor/)
 * Or:  make icons
 */

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dir   = dirname(fileURLToPath(import.meta.url));
const SVG_DIR = resolve(__dir, 'node_modules/pixelarticons/svg');
const OUT     = resolve(__dir, '../../internal/server/view/shared_icons_pixel.go');

// pixelarticons filename (no .svg)  →  Go constant suffix
const ICONS = [
  ['home',         'Home'],
  ['notes',        'Library'],
  ['image',        'Images'],
  ['message',      'Agent'],
  ['settings-cog-2', 'Settings'],
  ['search',       'Search'],
  ['bookmark',     'Bookmark'],
  ['reload',       'Reload'],
  ['file-text',    'FileText'],
  ['folder',       'Folder'],
  ['note',         'Note'],
  ['upload',       'Upload'],
  ['globe',        'Globe'],
  ['plus',         'Plus'],
  ['check',        'Check'],
  ['delete',       'Delete'],
  ['cancel',       'Cancel'],
  ['zap',          'Zap'],
];

function clean(raw) {
  let s = raw.trim();
  // strip xmlns, width, height attrs from outer <svg> tag
  s = s.replace(/\s+xmlns="[^"]*"/g, '');
  s = s.replace(/\s+width="\d+"/g, '');
  s = s.replace(/\s+height="\d+"/g, '');
  // strip <defs>…</defs> blocks (clip-path defs that are just full-rect no-ops)
  s = s.replace(/\s*<defs>[\s\S]*?<\/defs>/g, '');
  // strip clip-path="url(#…)" attributes left on <g> tags
  s = s.replace(/\s+clip-path="url\([^)]*\)"/g, '');
  // unwrap empty <g> tags: <g>\n  paths\n</g> → paths
  s = s.replace(/<g>\n([\s\S]*?)\n<\/g>/g, (_, inner) => inner);
  return s;
}

const lines = [
  'package view',
  '',
  '// Code generated by desktop-app/editor/gen-icons.mjs — DO NOT EDIT.',
  '// Run `make icons` to regenerate.',
  '',
];

let ok = 0, skip = 0;
for (const [file, suffix] of ICONS) {
  const path = resolve(SVG_DIR, `${file}.svg`);
  let raw;
  try {
    raw = readFileSync(path, 'utf8');
  } catch {
    console.warn(`  SKIP  ${file}.svg — not found`);
    skip++;
    continue;
  }
  const svg = clean(raw);
  lines.push(`// svgPx${suffix} is the pixelarticons "${file}" icon.`);
  lines.push(`const svgPx${suffix} = \`` + svg + `\``);
  lines.push('');
  console.log(`  OK    ${file}.svg → svgPx${suffix}`);
  ok++;
}

writeFileSync(OUT, lines.join('\n'), 'utf8');
console.log(`\nGenerated ${ok} icons (${skip} skipped) → ${OUT}`);
