package view

// Code generated by desktop-app/editor/gen-icons.mjs — DO NOT EDIT.
// Run `make icons` to regenerate.

// svgPxHome is the pixelarticons "home" icon.
const svgPxHome = `<svg fill="currentColor" viewBox="0 0 24 24">
  <path d="M4 20h16v2H4zm16-10h2v10h-2zM2 10h2v10H2zm2-2h2v2H4zm2-2h2v2H6zm2-2h2v2H8zm2-2h4v2h-4zm4 2h2v2h-2zm2 2h2v2h-2zm2 2h2v2h-2zM8 14h2v6H8zm2-2h4v2h-4zm4 2h2v6h-2z"/>
</svg>`

// svgPxLibrary is the pixelarticons "notes" icon.
const svgPxLibrary = `<svg fill="currentColor" viewBox="0 0 24 24">
  <path d="M6 8h2v12H6zM2 4h2v12H2zm18 4h2v8h-2zM8 6h12v2H8zM4 2h12v2H4zm14 14h2v2h-2zm-2 2h2v2h-2zm-8 2h8v2H8zm6-6h6v2h-6z"/>
  <path d="M14 14h2v6h-2zm2-10h2v2h-2zM4 16h2v2H4z"/>
</svg>`

// svgPxImages is the pixelarticons "image" icon.
const svgPxImages = `<svg fill="currentColor" viewBox="0 0 24 24">
  <path d="M4 2h16v2H4zm0 18h16v2H4zM2 4h2v16H2zm18 0h2v16h-2zm-4 8h2v2h-2zm-2 2h2v2h-2zm4 0h2v2h-2zm-8 0h2v2h-2zm2 2h2v2h-2zm2 2h2v2h-2z"/>
  <path d="M20 16h2v2h-2zM8 16h2v2H8zm-2 2h2v2H6zM8 6h2v2H8zM6 8h2v2H6zm2 2h2v2H8zm2-2h2v2h-2z"/>
</svg>`

// svgPxAgent is the pixelarticons "message" icon.
const svgPxAgent = `<svg fill="currentColor" viewBox="0 0 24 24">
  <path d="M20 2H4v2h16zm0 14H6v2h14zm2-12h-2v12h2zM4 4H2v18h2zm2 14H4v2h2z"/>
</svg>`

// svgPxSettings is the pixelarticons "settings-cog-2" icon.
const svgPxSettings = `<svg fill="currentColor" viewBox="0 0 24 24">
  <path d="M18 2h2v2h-2zM4 2h2v2H4zm16 20h-2v-2h2zM4 22h2v-2H4zM20 4h2v2h-2zM6 4h4v2H6zm12 16h-4v-2h4zM6 20h4v-2H6zM18 6h2v4h-2zM4 6h2v4H4zm16 12h-2v-4h2zM4 18h2v-4H4zM14 4h4v2h-4zM2 4h2v2H2zm20 16h-2v-2h2zM2 20h2v-2H2z"/>
  <path d="M8 2h2v4H8zm0 20h2v-4H8z"/>
  <path d="M8 2h8v2H8zm0 20h8v-2H8zM2 8h2v8H2zm20 8h-2V8h2z"/>
  <path d="M20 8h2v4h-2zM10 8h4v2h-4zm-2 2h2v4H8zm2 4h4v2h-4zm4-4h2v4h-2z"/>
</svg>`

// svgPxSearch is the pixelarticons "search" icon.
const svgPxSearch = `<svg fill="currentColor" viewBox="0 0 24 24">
  <path d="M22 22h-2v-2h2v2Zm-2-2h-2v-2h2v2Zm-6-2H6v-2h8v2Zm4 0h-2v-2h2v2ZM6 16H4v-2h2v2Zm10 0h-2v-2h2v2ZM4 14H2V6h2v8Zm14 0h-2V6h2v8ZM6 6H4V4h2v2Zm10 0h-2V4h2v2Zm-2-2H6V2h8v2Z"/>
</svg>`

// svgPxBookmark is the pixelarticons "bookmark" icon.
const svgPxBookmark = `<svg fill="currentColor" viewBox="0 0 24 24">
  <path d="M6 2h12v2H6zM4 4h2v18H4zm14 0h2v18h-2zm-2 16h2v2h-2zm-2-2h2v2h-2zm-8 2h2v2H6zm2-2h2v2H8zm2-2h4v2h-4z"/>
</svg>`

// svgPxReload is the pixelarticons "reload" icon.
const svgPxReload = `<svg fill="currentColor" viewBox="0 0 24 24">
  <path d="M16 4h2v6h-2zm-2-2h2v2h-2zm0 2h2v8h-2zM4 8H2v5h2z"/>
  <path d="M4 6h16v2H4zm4 14H6v-6h2zm2 2H8v-2h2zm0-2H8v-8h2zm10-4h2v-5h-2z"/>
  <path d="M20 18H4v-2h16z"/>
</svg>`

// svgPxFileText is the pixelarticons "file-text" icon.
const svgPxFileText = `<svg fill="currentColor" viewBox="0 0 24 24">
  <path d="M6 4H4v16h2zm10-2H6v2h10zm4 4h-2v14h2zm-2 14H6v2h12zM16 4h2v2h-2zm-4 0h2v6h-2z"/>
  <path d="M12 8h6v2h-6zm-4 8h8v2H8zm0-4h8v2H8zm0-4h2v2H8z"/>
</svg>`

// svgPxFolder is the pixelarticons "folder" icon.
const svgPxFolder = `<svg fill="currentColor" viewBox="0 0 24 24">
  <path d="M4 4h6v2H4zm0 14h16v2H4zM20 8h2v10h-2zM2 6h2v12H2zm8 0h10v2H10z"/>
</svg>`

// svgPxNote is the pixelarticons "note" icon.
const svgPxNote = `<svg fill="currentColor" viewBox="0 0 24 24">
  <path d="M2 4h2v16H2zm18 0h2v12h-2zM4 2h16v2H4zm14 14h2v2h-2zm-2 2h2v2h-2zM4 20h12v2H4zm10-8h6v2h-6zm-2 2h2v6h-2z"/>
</svg>`

// svgPxUpload is the pixelarticons "upload" icon.
const svgPxUpload = `<svg fill="currentColor" viewBox="0 0 24 24">
  <path d="M19 21H5v-2h14v2ZM5 19H3v-4h2v4Zm16 0h-2v-4h2v4ZM13 5h2v2h2v2h-4v8h-2V9H7V7h2V5h2V3h2v2Z"/>
</svg>`

// svgPxGlobe is the pixelarticons "globe" icon.
const svgPxGlobe = `<svg fill="currentColor" viewBox="0 0 24 24">
  <path d="M6 2h12v2H6zm0 18h12v2H6zM4 4h2v2H4zm5 0h2v2H9zm0 14h2v2H9zm4 0h2v2h-2zM7 6h2v12H7zm8 0h2v12h-2zm-2-2h2v2h-2zm7 0h-2v2h2zM2 6h2v12H2zm20 0h-2v12h2zM4 18h2v2H4zm16 0h-2v2h2z"/>
  <path d="M3 11h18v2H3z"/>
</svg>`

// svgPxPlus is the pixelarticons "plus" icon.
const svgPxPlus = `<svg fill="currentColor" viewBox="0 0 24 24">
  <path d="M13 11h7v2h-7v7h-2v-7H4v-2h7V4h2v7Z"/>
</svg>`

// svgPxCheck is the pixelarticons "check" icon.
const svgPxCheck = `<svg fill="currentColor" viewBox="0 0 24 24">
  <path d="M10 18H8v-2h2v2Zm-2-2H6v-2h2v2Zm4-2v2h-2v-2h2Zm-6 0H4v-2h2v2Zm8 0h-2v-2h2v2Zm2-2h-2v-2h2v2Zm2-2h-2V8h2v2Zm2-2h-2V6h2v2Z"/>
</svg>`

// svgPxDelete is the pixelarticons "delete" icon.
const svgPxDelete = `<svg fill="currentColor" viewBox="0 0 24 24">
  <path d="M6 7h2v2H6zm14 0h2v10h-2zM8 5h12v2H8zM4 9h2v2H4zm-2 2h2v2H2zm2 2h2v2H4zm2 2h2v2H6zm2 2h12v2H8zm6-6h2v2h-2zm2 2h2v2h-2zm0-4h2v2h-2zm-4 4h2v2h-2zm0-4h2v2h-2z"/>
</svg>`

// svgPxCancel is the pixelarticons "cancel" icon.
const svgPxCancel = `<svg fill="currentColor" viewBox="0 0 24 24">
  <path d="M6 2h12v2H6zm0 18h12v2H6zM2 6h2v12H2zm18 0h2v12h-2zm-2-2h2v2h-2zm-2 2h2v2h-2zm-2 2h2v2h-2zm-2 2h2v2h-2zm-2 2h2v2h-2zm-2 2h2v2H8zm-2 2h2v2H6zm12 2h2v2h-2zM4 4h2v2H4zm0 14h2v2H4z"/>
</svg>`

// svgPxZap is the pixelarticons "zap" icon.
const svgPxZap = `<svg fill="currentColor" viewBox="0 0 24 24">
  <path d="M4 13h8v6h2v2h-2v2h-2v-8H2v-4h2v2Zm12 6h-2v-2h2v2Zm2-2h-2v-2h2v2Zm2-2h-2v-2h2v2Zm-6-6h8v4h-2v-2h-8V5h-2V3h2V1h2v8Zm-8 2H4V9h2v2Zm2-2H6V7h2v2Zm2-2H8V5h2v2Z"/>
</svg>`
